let tournament=document.getElementById("tournament");
let bubblegum=document.getElementById("bubblegum");
let wood=document.getElementById("wood");
let azure=document.getElementById("azure");
let square=document.getElementsByClassName("square");
let dark=document.getElementsByClassName("Dark");
let white=document.getElementsByClassName("Light");

bubblegum.addEventListener("click",()=>{
    Array.from(dark).forEach(element=>{
        if(element.classList.contains("green")==true){
            element.classList.remove("green")
            element.classList.add("bubblegum")
            dark=document.getElementsByClassName("bubblegum");
        }
        if(element.classList.contains("wood")==true){
            element.classList.remove("wood")
            element.classList.add("bubblegum")
            dark=document.getElementsByClassName("bubblegum");
        }
        if(element.classList.contains("azure")==true){
            element.classList.remove("azure")
            element.classList.add("bubblegum")
            dark=document.getElementsByClassName("bubblegum");
        }
    })
    Array.from(white).forEach(element=>{
        if(element.classList.contains("white")==true){
            element.classList.remove("white");
            element.classList.add("bubblegumWhite");
            white=document.getElementsByClassName("bubblegumWhite")
        }
        if(element.classList.contains("woodWhite")==true){
            element.classList.remove("woodWhite");
            element.classList.add("bubblegumWhite");
            white=document.getElementsByClassName("bubblegumWhite")
        }
        if(element.classList.contains("azureWhite")==true){
            element.classList.remove("azureWhite");
            element.classList.add("bubblegumWhite");
            white=document.getElementsByClassName("bubblegumWhite")
        }
    })
})
wood.addEventListener("click",()=>{
    Array.from(dark).forEach(element=>{
        if(element.classList.contains("green")==true){
            element.classList.remove("green")
            element.classList.add("wood")
            dark=document.getElementsByClassName("wood");
        }
        if(element.classList.contains("bubblegum")==true){
            element.classList.remove("bubblegum")
            element.classList.add("wood")
            dark=document.getElementsByClassName("wood");
        }
        if(element.classList.contains("azure")==true){
            element.classList.remove("azure")
            element.classList.add("wood")
            dark=document.getElementsByClassName("wood");
        }
    })
    Array.from(white).forEach(element=>{
        if(element.classList.contains("white")==true){
            element.classList.remove("white");
            element.classList.add("woodWhite");
            white=document.getElementsByClassName("woodWhite")
        }
        if(element.classList.contains("bubblegumWhite")==true){
            element.classList.remove("bubblegumWhite");
            element.classList.add("woodWhite");
            white=document.getElementsByClassName("woodWhite")
        }
        if(element.classList.contains("azureWhite")==true){
            element.classList.remove("azureWhite");
            element.classList.add("woodWhite");
            white=document.getElementsByClassName("woodWhite")
        }
    })
})
azure.addEventListener("click",()=>{
    Array.from(dark).forEach(element=>{
        if(element.classList.contains("green")==true){
            element.classList.remove("green")
            element.classList.add("azure");
            dark=document.getElementsByClassName("azure");
        }
        if(element.classList.contains("bubblegum")==true){
            element.classList.remove("bubblegum")
            element.classList.add("azure")
            dark=document.getElementsByClassName("azure");
        }
        if(element.classList.contains("wood")==true){
            element.classList.remove("wood")
            element.classList.add("azure")
            dark=document.getElementsByClassName("azure");
        }
    })
    Array.from(white).forEach(element=>{
        if(element.classList.contains("white")==true){
            element.classList.remove("white");
            element.classList.add("azureWhite");
            white=document.getElementsByClassName("azureWhite")
        }
        if(element.classList.contains("bubblegumWhite")==true){
            element.classList.remove("bubblegumWhite");
            element.classList.add("azureWhite");
            white=document.getElementsByClassName("azureWhite")
        }
        if(element.classList.contains("woodWhite")==true){
            element.classList.remove("woodWhite");
            element.classList.add("azureWhite");
            white=document.getElementsByClassName("azureWhite")
        }
    })
})
tournament.addEventListener("click",()=>{
    Array.from(dark).forEach(element=>{
        if(element.classList.contains("azure")==true){
            element.classList.remove("azure")
            element.classList.add("green");
            dark=document.getElementsByClassName("green");
        }
        if(element.classList.contains("bubblegum")==true){
            element.classList.remove("bubblegum")
            element.classList.add("green")
            dark=document.getElementsByClassName("green");
        }
        if(element.classList.contains("wood")==true){
            element.classList.remove("wood")
            element.classList.add("green")
            dark=document.getElementsByClassName("green");
        }
    })
    Array.from(white).forEach(element=>{
        if(element.classList.contains("azureWhite")==true){
            element.classList.remove("azureWhite");
            element.classList.add("white");
            white=document.getElementsByClassName("white")
        }
        if(element.classList.contains("bubblegumWhite")==true){
            element.classList.remove("bubblegumWhite");
            element.classList.add("white");
            white=document.getElementsByClassName("white")
        }
        if(element.classList.contains("woodWhite")==true){
            element.classList.remove("woodWhite");
            element.classList.add("white");
            white=document.getElementsByClassName("white")
        }
    })
})